import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { reveal as Menu } from "react-burger-menu";

export default function Home({ events }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Wildfire</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Menu className={styles.nav}>
        <a id="home" className="menu-item" href="/">
          Home
        </a>
        <a id="about" className="menu-item" href="/about">
          About
        </a>
        <a id="contact" className="menu-item" href="/contact">
          Contact
        </a>
        <a className="menu-item--small" href="">
          Settings
        </a>
      </Menu>

      <main className={styles.main}>
        <video autoPlay loop muted infinite className={styles.video}>
          <source
            src="https://res.cloudinary.com/dsdpn6tzq/video/upload/v1670360021/Website/new%20site/New_website_header_ksrcqi.mp4"
            type="video/mp4"
          />
        </video>
        <Link href={"/events"} className={styles.events}>
          Events
        </Link>
      </main>
    </div>
  );
}
